### ISSUE TITLE
Maybe need a better name

### ISSUE THREAD

**Issue by pakastin** [testonjs/teston#3]
Suggestions? 🙂

**Comment by akx** [comment]
`kassitest`? 😁

**Comment by michaelonubogu** [comment]
Testi-mc-testface?

**Comment by bebraw** [comment]
karmicle

**Comment by philipjscott** [comment]
ava :^)

**Comment by andersonjoseph** [comment]
testelci

**Comment by TeHMoroS** [comment]
How about "jsicle" or rather "jcicle" (as in i++cicle?). It has that nice "JS" vibe when pronouncing.

**Comment by pakastin** [comment]
But why ”cicle” then?

**Comment by TeHMoroS** [comment]
@pakastin Don't know. Just wanted to at least preserve a part of the name already used. :P

**Comment by pakastin** [comment]
Haha, no need for that – unless it’s the ”test” part 😄

**Comment by pakastin** [comment]
Testicle is now Teston! 🎉

**Comment by TeHMoroS** [comment]
@pakastin Nice. :)

**Comment by ghost** [comment]
lol, @pakastin sure has a good taste for naming stuff

**Comment by pakastin** [comment]
Haha, the initial name was just a bad friday joke 😄

**Comment by hakanols** [comment]
Funny thing! I found testicle on https://www.pika.dev/npm/testicle
and it looked suspiciously like Teston. I was going to report it to you, @pakastin, as a theft of your fine work.

**Comment by TeHMoroS** [comment]
@hakanols I wouldn't worry about that. Seems Pika just has it's own NPM browser. You'll find the exact same entry at the NPM site: https://www.npmjs.com/package/testicle (one thing I find a bit strange: they don't display any info about the package author or origin).

**Comment by pakastin** [comment]
Testicle was Teston's original name, so that's just Teston :D

**Comment by hakanols** [comment]
Yes I noticed that it was the old name. A magnificent name. Perhaps it is time to deprecate the Testicle NPM package and link to Teston?

**Comment by pakastin** [comment]
Ah yeah, haven't realized that..
